### PR TITLE
Add Factorio

### PR DESCRIPTION
**Pull request by dejan1024**
Factorio supports LightSync.
Example: https://www.reddit.com/r/factorio/comments/j29sy6/i_just_noticed_this_on_my_logitech_keyboard_when/

### CODE REVIEW

**Comment by xyj-3** [comment]
Thank you! Can you rearrange so that the name is in alphabetical order?

**Comment by dejan1024** [comment]
It wasn't already? :O Sorry about that, my bad.

**Comment by xyj-3** [comment]
Thanks, merged.

**Comment by xyj-3** [comment]
Hm, sorry, I'm not actually trying to revert. I wanted to mark as approved before merging so I was trying to see if I could do so retroactively.

**Pull request merged**
